import Team1 from '../assets/images/projects_danpung_2024/team1.jpg';
import Team2 from '../assets/images/projects_danpung_2024/team2.jpg';
import Team3 from '../assets/images/projects_danpung_2024/team3.jpg';
import Team4 from '../assets/images/projects_danpung_2024/team4.jpg';
import Team5 from '../assets/images/projects_danpung_2024/team5.png';
import Team6 from '../assets/images/projects_danpung_2024/team6.jpg';
import Team7 from '../assets/images/projects_danpung_2024/team7.png';
import Team8 from '../assets/images/projects_danpung_2024/team8.png';
import Team9 from '../assets/images/projects_danpung_2024/team9.jpg';
import Team10 from '../assets/images/projects_danpung_2024/team10.jpg';
import Team11 from '../assets/images/projects_danpung_2024/team11.jpg';
import Team12 from '../assets/images/projects_danpung_2024/team12.jpg';
import Team13 from '../assets/images/projects_danpung_2024/team13.jpg';
import Team14 from '../assets/images/projects_danpung_2024/team14.jpg';
import Team15 from '../assets/images/projects_danpung_2024/team15.png';
import Team16 from '../assets/images/projects_danpung_2024/team16.png';
import Team17 from '../assets/images/projects_danpung_2024/team17.png';
import Team18 from '../assets/images/projects_danpung_2024/team18.png';
import Team19 from '../assets/images/projects_danpung_2024/team19.png';
import Team20 from '../assets/images/projects_danpung_2024/team20.png';
import Team21 from '../assets/images/projects_danpung_2024/team21.png';
import Team22 from '../assets/images/projects_danpung_2024/team22.png';
import Team23 from '../assets/images/projects_danpung_2024/team23.png';
import Team24 from '../assets/images/projects_danpung_2024/team24.png';
import Team25 from '../assets/images/projects_danpung_2024/team25.png';
import Team26 from '../assets/images/projects_danpung_2024/team26.png';
import Team27 from '../assets/images/projects_danpung_2024/team27.png';
import Team28 from '../assets/images/projects_danpung_2024/team28.png';
import Team29 from '../assets/images/projects_danpung_2024/team29.jpg';
import Team30 from '../assets/images/projects_danpung_2024/team30.jpg';
import Team31 from '../assets/images/projects_danpung_2024/team31.jpg';
import Team32 from '../assets/images/projects_danpung_2024/team32.jpg';
import Team33 from '../assets/images/projects_danpung_2024/team33.jpg';
import Team34 from '../assets/images/projects_danpung_2024/team34.jpg';
import Team35 from '../assets/images/projects_danpung_2024/team35.png';
import Team36 from '../assets/images/projects_danpung_2024/team36.jpg';
import Team37 from '../assets/images/projects_danpung_2024/team37.jpg';
import Team38 from '../assets/images/projects_danpung_2024/team38.jpg';
import Team39 from '../assets/images/projects_danpung_2024/team39.png';
import Team40 from '../assets/images/projects_danpung_2024/team40.jpg';
import Team41 from '../assets/images/projects_danpung_2024/team41.jpg';
import Team42 from '../assets/images/projects_danpung_2024/team42.jpg';
import Team43 from '../assets/images/projects_danpung_2024/team43.webp';
import Team44 from '../assets/images/projects_danpung_2024/team44.jpg';
import Team45 from '../assets/images/projects_danpung_2024/team45.jpg';
import Team46 from '../assets/images/projects_danpung_2024/team46.jpg';
import Team47 from '../assets/images/projects_danpung_2024/team47.jpg';
import Team48 from '../assets/images/projects_danpung_2024/team48.jpg';
import Team49 from '../assets/images/projects_danpung_2024/team49.jpg';
import Team50 from '../assets/images/projects_danpung_2024/team50.png';
import Team51 from '../assets/images/projects_danpung_2024/team51.jpg';
import Team52 from '../assets/images/projects_danpung_2024/team52.jpg';
import Team53 from '../assets/images/projects_danpung_2024/team53.jpg';
import Team54 from '../assets/images/projects_danpung_2024/team54.jpg';
import Team55 from '../assets/images/projects_danpung_2024/team55.jpg';
import Team56 from '../assets/images/projects_danpung_2024/team56.jpg';
import Team58 from '../assets/images/projects_danpung_2024/team58.png';
import Team59 from '../assets/images/projects_danpung_2024/team59.png';
import Team60 from '../assets/images/projects_danpung_2024/team60.png';
import Team61 from '../assets/images/projects_danpung_2024/team61.png';
import Team62 from '../assets/images/projects_danpung_2024/team62.png';
import Team63 from '../assets/images/projects_danpung_2024/team63.png';
import Team64 from '../assets/images/projects_danpung_2024/team64.png';
import Team65 from '../assets/images/projects_danpung_2024/team65.png';
import Team66 from '../assets/images/projects_danpung_2024/team66.png';
import Team67 from '../assets/images/projects_danpung_2024/team67.png';

const DanpungProject2024Data = [
  {
    award: '대상',
    title: '내일모래',
    content: '자립준비청년의 일상을 비추는 봉사자의 목소리',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOON_TEAM_22_BE/tree/release/%2352',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_22_FE',
    releaseLink: '',
    image: Team22,
    pm: '박주현(성신여대)',
    design: '김수연(성신여대)',
    frontend: ['박정빈(국민대)', '봉지수(아주대)'],
    backend: ['노유성(가천대)', '심세원(가천대)'],
  },
  {
    award: '최우수상',
    title: '아이보리',
    content: 'AI OCR 기반 질병감염아동돌봄 서비스 신청  플랫폼',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_15_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_15_FE',
    releaseLink: 'https://danpoong-ivory.vercel.app/',
    image: Team15,
    pm: '김민서(성균관대)',
    design: '권기남(한성대)',
    frontend: ['김서윤(덕성여대)', '김태건(성균관대)'],
    backend: ['이주연(한성대)', '강기환(한국공학대)'],
  },
  {
    award: '최우수상',
    title: '마이무',
    content: '결식 아동에게 잊지 못할 밥 한 끼를',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_50_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_50_FE',
    releaseLink: '',
    image: Team50,
    pm: '',
    design: '손주영(한양대(에리카))',
    frontend: ['이현진(성신여대)', '이재림(성균관대)', '한승우(명지대)'],
    backend: ['이동건(경북대)', '노혜능(경희대)'],
  },
  {
    award: '우수상',
    title: '온정',
    content: '소상공인 선행 동참 플랫폼',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_13_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_13_FE',
    releaseLink: '',
    image: Team13,
    pm: '마소영(국민대)',
    design: '오유나(홍익대(세종))',
    frontend: ['김동현(단국대)', '안세홍(국민대)'],
    backend: ['장동겸(동국대)', '정은지(동국대)'],
  },
  {
    award: '우수상',
    title: '오르빛',
    content: '당신의 미래를 비추는 별자리',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_52_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOON_TEAM_52_FE',
    releaseLink: '',
    image: Team52,
    pm: '전유선(국민대)',
    design: '이한별(가천대)',
    frontend: ['황석영(인하대)', '권도훈(인천대)'],
    backend: ['김시원(한국외대)', '구태형(경희대)'],
  },
  {
    award: '로티파일즈 특별상',
    title: '장부리치',
    content: '소상공인과 소비자를 위한 손쉬운 장부 관리의 시작',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_5_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_5_FE_1',
    releaseLink: '',
    image: Team5,
    pm: '고주연(서울여대)',
    design: '김가현(중앙대)',
    frontend: ['변상우(서울과기대)', '피유진(서울과기대)'],
    backend: ['이재혁(서울과기대)', '오현우(한국외대)'],
  },
  {
    award: '',
    title: '유행',
    content: '내가 만드는 지역 행사',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOON_TEAM_1_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_1_FE',
    releaseLink: '',
    image: Team1,
    pm: '김기루(울산대)',
    design: '채은영(숭실대)',
    frontend: ['이정선(동국대)', '최연우(아주대)'],
    backend: ['김승윤(한양대(에리카))', '전재연(한양대(에리카))'],
  },
  {
    award: '',
    title: 'MOA',
    content: '지역 순환 경제를 유도하고 사회적 가치를 조명하는 펀딩 플랫폼',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_2_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_2_FE',
    releaseLink: 'https://2024-danpoong-team-2-fe.vercel.app/',
    image: Team2,
    pm: '진현주(홍익대(세종))',
    design: '진현주(홍익대(세종))',
    frontend: ['유현상(중부대)', '박수민(숙명여대)', '조용민(숭실대)'],
    backend: ['최기웅(성공회대)', '문성욱(호서대)'],
  },
  {
    award: '',
    title: 'OutOfCity',
    content: '유명 관광지가 아니어도 재미있을 수 있잖아!',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_3_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_3_FE',
    releaseLink: '',
    image: Team3,
    pm: '채윤지(경희대)',
    design: '오지샘(경희대)',
    frontend: ['이수민(숭실대)', '배수연(한양대(에리카))'],
    backend: ['오현석(동국대)', '김영훈(청주대)'],
  },
  {
    award: '',
    title: '소확행',
    content: '지역 생산자와 B2B 고객을 연결하는 정기 계약 플랫폼',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_4_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_4_FE',
    releaseLink: 'https://smallhappy.vercel.app/',
    image: Team4,
    pm: '제현우(가천대)',
    design: '',
    frontend: ['김현아(한국외대)', '신태일(서경대)'],
    backend: ['전민주(경기대)', '현진용(성공회대)'],
  },
  {
    award: '',
    title: 'ONFEST',
    content: '우리 지역의 축제를 한눈에 !',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_6_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_6_FE',
    releaseLink: '',
    image: Team6,
    pm: '김유빈(울산대)',
    design: '박우석(광운대)',
    frontend: ['박지윤(숭실대)', '배진우(울산대)'],
    backend: ['백소미(경기대)', '한현규(동국대)'],
  },
  {
    award: '',
    title: 'Soenter',
    content: '지역의 가치를 더하다, 사회적 기업과 함께하다!',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_7_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_7_FE',
    releaseLink: 'https://soenter.vercel.app/',
    image: Team7,
    pm: '김서현(성신여대)',
    design: '김루시아(국민대)',
    frontend: ['이나영(성신여대)'],
    backend: ['권윤재(서경대)', '서하은(동국대)'],
  },
  {
    award: '',
    title: 'Buddy',
    content: '나만의 든든한 자립 친구',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_8_BE1',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_8_FE',
    releaseLink: 'https://danpoong-buddy.vercel.app/',
    image: Team8,
    pm: '고다윤(경기대)',
    design: '최현비(인하대)',
    frontend: ['이은지(서울과기대)', '장민수(가천대)'],
    backend: ['구혜승(서울여대)', '이창규(세종대)'],
  },
  {
    award: '',
    title: 'LOCC',
    content: '지방의 숨겨진 로컬 크리에이터들을 한 손에서 잠금해제',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_9_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_9_FE',
    releaseLink: '',
    image: Team9,
    pm: '김지호(동국대)',
    design: '김가연(한국공학대)',
    frontend: ['성호은(동국대)', '우은진(경희대)'],
    backend: ['임채영(서울과기대)', '황종훈(경희대)'],
  },
  {
    award: '',
    title: '오달지다',
    content: '사용자 맞춤 지역축제 정보제공',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_10_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_10_FE',
    releaseLink: '',
    image: Team10,
    pm: '김선희(창원대)',
    design: '',
    frontend: ['곽동선(동양미래대)', '김윤선(전남대)'],
    backend: ['송민혁(중앙대)', '전찬훈(대구가톨릭대)'],
  },
  {
    award: '',
    title: '농담',
    content: '버려질 뻔 했던 농산물의 이야기',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_11_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_11_FE',
    releaseLink: '',
    image: Team11,
    pm: '선예지(숙명여대)',
    design: '백건희(경상국립대)',
    frontend: ['김충영(가천대)', '정희연(가천대)'],
    backend: ['김동균(성공회대)', '최원준(한국공학대)'],
  },
  {
    award: '',
    title: 'course pick!',
    content: 'AI기반 여행 코스 추천 서비스',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_12_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_12_FE',
    releaseLink: '',
    image: Team12,
    pm: '김이영(서울과기대)',
    design: '정지영(울산대)',
    frontend: ['나민혁(울산대)', '조건희(서울과기대)'],
    backend: ['이남규(호서대)', '안지현(경희대)'],
  },
  {
    award: '',
    title: '동그라ME',
    content: '이동약자를 위한 여행지도',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_14_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_14_FE',
    releaseLink: 'https://www.circleme.site/',
    image: Team14,
    pm: '박민지(울산대)',
    design: '박보영(대구가톨릭대)',
    frontend: ['최승아(광운대)', '우진용(경북대)'],
    backend: ['김민준(경상국립대)', '송재훈(경기대)'],
  },
  {
    award: '',
    title: '모행! 모두의 여행',
    content: 'AI 생성 배리어프리 여행 코스 제공 서비스',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_16_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_16_FE1',
    releaseLink: '',
    image: Team16,
    pm: '정희원(성신여대)',
    design: '이영지(국민대)',
    frontend: ['박동재(국민대)', '김다현(한성대)'],
    backend: ['김서진(성신여대)', '이건무(서경대)'],
  },
  {
    award: '',
    title: '문화한상',
    content: '지역 외국인과 문화를 교류하며 소통하는 플랫폼',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_17_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_17_FE',
    releaseLink: 'https://www.munhwahansang.com/',
    image: Team17,
    pm: '김아름(전남대)',
    design: '장효승(한양대(에리카))',
    frontend: ['이윤정(서경대)'],
    backend: ['이승재(세종대)', '류연경(창원대)'],
  },
  {
    award: '',
    title: '기억의 나무',
    content: `당신의 기억의 열매를 맺는 특별한 공간, '기억의 나무'와 함께하세요.`,
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_18_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_18_FE',
    releaseLink: 'https://tree-of-memory.vercel.app',
    image: Team18,
    pm: '',
    design: '이하은(경상국립대)',
    frontend: ['현지현(경기대)', '임수미(한성대)'],
    backend: ['최재혁(창원대)', '황현서(동국대)', '김택천(세종대)'],
  },
  {
    award: '',
    title: 'AnyoneToo',
    content: `'AnyoneToo'는 소외된 이웃이 직접 만든 물건을 팔 수 있는 기회를 제공하여 자립의 발판을 만들어 갑니다`,
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_19_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_19_FE',
    releaseLink: 'https://anyonetoo.site',
    image: Team19,
    pm: '최민지(인천대)',
    design: '허수언(울산대)',
    frontend: ['민동명(서경대)', '한지원(덕성여대)'],
    backend: ['서윤주(경희대)', '한준서(인천대)'],
  },
  {
    award: '',
    title: 'MixMix',
    content: 'MixMix는 유학생들을 위한 언어, 문화, 네트워킹 서비스입니다.',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_2_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_2_FE',
    releaseLink: 'https://2024-danpoong-team-2-fe.vercel.app/',
    image: Team20,
    pm: '김민상(서울과기대)',
    design: '천현주(창원대)',
    frontend: ['김지원(광운대)', '최도현(동양미래대)'],
    backend: ['차서윤(서울과기대)', '최인호(성공회대)'],
  },
  {
    award: '',
    title: '척척 이지',
    content: '디지털 소외계층의 결제 독립을 위한, 무인 결제 학습 시스템 <주문?EASY!>',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_20_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_20_FE',
    releaseLink: '',
    image: Team21,
    pm: '양희선(서울여대)',
    design: '배지우(경희대)',
    frontend: ['장영주(경희대)', '노성원(한국외대)'],
    backend: ['이지원(서울과기대)', '신중은(서울과기대)'],
  },
  {
    award: '',
    title: '의사손주',
    content: '노인 의료디지털 소외 개선 서비스. 내손안의 AI주치의, 의사손주',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_23_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_23_FE',
    releaseLink: '',
    image: Team23,
    pm: '송지혜(가천대)',
    design: '김다혜(동국대)',
    frontend: ['이재윤(순천향대)', '조성원(경기대)'],
    backend: ['정우주(전남대)', '김민아(경희대)'],
  },
  {
    award: '',
    title: '이음',
    content: '결식아동을 따뜻한 한 끼로 이어주다',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_24_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_24_FE',
    releaseLink: 'https://ieum-24.vercel.app',
    image: Team24,
    pm: '',
    design: '김보경(서울과기대)',
    frontend: ['김도윤(세종대)', '이지희(동국대)', '박희진(경기대)'],
    backend: ['김규리(동국대)', '임우진(세종대)'],
  },
  {
    award: '',
    title: 'FlakeIDE',
    content: '코딩을 시작하는 누구나 쉽고 저렴하게 사용할 수 있는 웹 기반의 교육용 IDE 서비스',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOON_TEAM_25_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOON_TEAM_25_FE',
    releaseLink: '',
    image: Team25,
    pm: '조은애(명지대)',
    design: '최아령(경상국립대)',
    frontend: ['임채민(순천향대)', '서유빈(단국대)'],
    backend: ['이성진(명지대)', '조규림(성공회대)'],
  },
  {
    award: '',
    title: 'ReQuest',
    content: 'IT업계 취업을 위한 AI과제 전형 도우미',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOON_TEAM_26_SERVICE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOON_TEAM_26_SERVICE',
    releaseLink: 'https://dev-re-quest.eatsteak.dev/',
    image: Team26,
    pm: '이지유(건국대)',
    design: '마예린(홍익대(세종))',
    frontend: ['공민제(숭실대)', '임광수(한국공학대)'],
    backend: ['김정래(세종대)', '구효민(숭실대)'],
  },
  {
    award: '',
    title: 'LUCKIT',
    content: '운세를 통한 작은 성취로 성장하는 투두리스트',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_27_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_27_FE',
    releaseLink: '',
    image: Team27,
    pm: '마재훈(경기대)',
    design: '하수정(숙명여대)',
    frontend: ['전도연(경희대)', '이승훈(광운대)'],
    backend: ['안준영(성공회대)', '박진홍(서울과기대)'],
  },
  {
    award: '',
    title: 'Lively',
    content: '고립·은둔 청년을 위한 사회 복귀 지원 애플리케이션',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_28_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOON_TEAM_28_FE',
    releaseLink: '',
    image: Team28,
    pm: '장예원(서경대)',
    design: '이한비(덕성여대)',
    frontend: ['이보배(전남대)', '나현(서울여대)'],
    backend: ['이지수(한국외대)', '진미나(전남대)'],
  },
  {
    award: '',
    title: 'GlobalNest',
    content: '외국인 노동자의 인권을 위한 다국어 지원 소통창구와 청원 플랫폼',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOON_TEAM_29_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_29_FE',
    releaseLink: '',
    image: Team29,
    pm: '김신영(동양미래대)',
    design: '서석민(경기대)',
    frontend: ['이유진(숭실대)', '신혁수(세종대)'],
    backend: ['김병웅(공주대)', '이동영(숭실대)'],
  },
  {
    award: '',
    title: '레디, 액션!',
    content: '자립의 첫걸음 자가진단으로 함께 준비하자!',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOON_TEAM_30_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_30_FE',
    releaseLink: '',
    image: Team30,
    pm: '정준경(상명대(천안))',
    design: '정다연(가천대)',
    frontend: ['안나경(한국공학대)', '이준석(공주대)'],
    backend: ['정순재(상명대(천안))', '홍선아(한국공학대)'],
  },
  {
    award: '',
    title: 'WithU',
    content: '힘든 세상을 살아가고 있는 우리들을 위한 가족 소통 서비스, WithU',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_31_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_31_FE',
    releaseLink: '',
    image: Team31,
    pm: '강민서(성신여대)',
    design: '조민정(홍익대(세종))',
    frontend: ['김현서(한성대)', '허윤호(서경대)'],
    backend: ['김수훈(광운대)', '서현은(서경대)'],
  },
  {
    award: '',
    title: '유맵',
    content: '위치 기반 청년 맞춤형 정책 추천 서비스',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_32_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_32_FE',
    releaseLink: 'http://400cc.araas.ai/',
    image: Team32,
    pm: '조맑음(인하대)',
    design: '유은재(성신여대)',
    frontend: ['민지우(가천대)', '고석환(광운대)'],
    backend: ['이현동(상명대(천안))', '이유진(상명대(천안))'],
  },
  {
    award: '',
    title: '일트',
    content: '객관적으로 안내하는 일트',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_33_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_33_FE',
    releaseLink: '',
    image: Team33,
    pm: '손영동(창원대)',
    design: '황애라(숭실대)',
    frontend: ['이만재(성공회대)'],
    backend: ['강형준(인천대)', '황보재윤(대구가톨릭대)'],
  },
  {
    award: '',
    title: 'Reboot Office',
    content: '고립은둔청년의 일상회복을 위한 서비스',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_34_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_34_FE',
    releaseLink: '',
    image: Team34,
    pm: '이재형(명지대)',
    design: '이희균(대구가톨릭대)',
    frontend: ['강지희(경상국립대)', '홍규진(동국대)'],
    backend: ['정연재(상명대(천안))', '박민기(동국대)'],
  },
  {
    award: '',
    title: '자소플',
    content: '퍼즐맞추듯 자소서를 자동작성해주는 AI',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_35_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_35_FE',
    releaseLink: '',
    image: Team35,
    pm: '이상협(울산대)',
    design: '이상협(울산대)',
    frontend: ['윤가은(공주대)', '김다은(순천향대)', '최세연(한국공학대)'],
    backend: ['이지원(성신여대)', '서정호(울산대)'],
  },
  {
    award: '',
    title: 'YE;Summit',
    content: '청년 창업가들을 위한 PT 및 투자 연결 플랫폼',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOON_TEAM_36_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOON_TEAM_36_FE',
    releaseLink: '',
    image: Team36,
    pm: '',
    design: '김하늘(숭실대)',
    frontend: ['최규리(한국외대)', '유지희(한국외대)', '양석준(국민대)'],
    backend: ['손수민(가천대)', '이예은(성공회대)'],
  },
  {
    award: '',
    title: 'Teamate',
    content: '나만의 팀 단짝을 찾아주는 서비스',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_37_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_37_FE',
    releaseLink: '',
    image: Team37,
    pm: '',
    design: '백지연(동국대)',
    frontend: ['문지원(한양대(에리카))', '장연주(서울여대)'],
    backend: ['전창하(서울과기대)', '유다영(국민대)'],
  },
  {
    award: '',
    title: '펀드부스트',
    content: '기업과의 공동 펀딩을 통해 청년들의 아이디어 실현에 기여하는 펀드부스트',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_38_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_38_FE',
    releaseLink: '',
    image: Team38,
    pm: '박재영(경북대)',
    design: '정유나(홍익대(세종))',
    frontend: ['현용찬(상명대(천안))', '성지훈(상명대(천안))'],
    backend: ['서지우(성신여대)', '최숙희(숭실대)'],
  },
  {
    award: '',
    title: '손길',
    content: '가족 돌봄 청년을 위한 돌봄 일정 관리 앱',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_39_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_39_FE',
    releaseLink: '',
    image: Team39,
    pm: '최진석(건국대)',
    design: '송은선(서울여대)',
    frontend: ['김희정(창원대)', '남기범(호서대)'],
    backend: ['강경아(경상국립대)', '최영인(삼육대)'],
  },
  {
    award: '',
    title: '모두의 길 ',
    content: '함께해서 더 걷기 좋은',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_40_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_40_FE',
    releaseLink: '',
    image: Team40,
    pm: '홍서연(가천대)',
    design: '',
    frontend: ['김미주(덕성여대)', '박상민(명지대)'],
    backend: ['양해정(인하공업전문대)', '임승우(한양대(에리카))'],
  },
  {
    award: '',
    title: '다갈꼬양',
    content: '소상공인과 소비자를 이어주고 지역 경제와 전통 문화 활성화에 기여하는 플랫폼',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_41_BE',
    frontendLink: 'https://github.com/9oormthon-univ/9oormthon-univ-2024_DANPOON_TEAM_41_FE',
    releaseLink: '',
    image: Team41,
    pm: '박서영(동국대)',
    design: '이경애(중부대)',
    frontend: ['원동휘(울산대)', '정영아(울산대)'],
    backend: ['노은빈(명지대)', '황치연(광운대)'],
  },
  {
    award: '',
    title: 'SWIPO',
    content: '2030세대의 지역 상생 가맹점 이용률 저조 개선 플랫폼 서비스',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_42_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOON_TEAM_42_FE',
    releaseLink: '',
    image: Team42,
    pm: '민예림(국민대)',
    design: '윤다희(울산대)',
    frontend: ['엄재웅(울산대)', '박지윤(숭실대)'],
    backend: ['강두오(성공회대)', '유준호(경상국립대)'],
  },
  {
    award: '',
    title: 'Carely',
    content: '돌봄의 순간을 하나로 연결하다',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_43_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_43_FE',
    releaseLink: 'https://carely-seven.vercel.app/login',
    image: Team43,
    pm: '박성민(경기대)',
    design: '송연우(경기대)',
    frontend: ['정지오(한양대(에리카))', '강신영(성신여대)'],
    backend: ['김은서(덕성여대)', '이규민(덕성여대)'],
  },
  {
    award: '',
    title: '집콕',
    content: '청년들을 위한 부동산 도우미!',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_44_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_44_FE',
    releaseLink: '',
    image: Team44,
    pm: '',
    design: '조원희(성신여대)',
    frontend: ['김나희(인하공업전문대)', '노예원(가천대)'],
    backend: ['강우주(단국대)', '유승완(동양미래대)', '강지석(한국공학대)'],
  },
  {
    award: '',
    title: '무무',
    content: 'Coding land - 모두를 위한 즐거운 코딩 교육',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_45_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_45_FE',
    releaseLink: '',
    image: Team45,
    pm: '',
    design: '김수진(홍익대(세종))',
    frontend: ['박지원(한성대)', '조은채(아주대)'],
    backend: ['한예지(성신여대)', '김원정(인천대)', '안정후(서울과학기술대)'],
  },
  {
    award: '',
    title: 'Book두칠성',
    content: '독서 공유 플랫폼',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_46_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_46_FE',
    releaseLink: '',
    image: Team46,
    pm: '',
    design: '유재우(홍익대(세종))',
    frontend: ['류지혜(중부대)', '전주은(중부대)'],
    backend: ['민정준(한국공학대)', '정성호(경희대)'],
  },
  {
    award: '',
    title: '공주',
    content: '주차 공간 부족 해결을 위한 공유 주차장 서비스',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_47_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_47_FE',
    releaseLink: '',
    image: Team47,
    pm: '',
    design: '김민지(가톨릭대)',
    frontend: ['정윤석(호서대)'],
    backend: ['이진성(공주대)'],
  },
  {
    award: '',
    title: 'Mesh',
    content: '지역을 넘어 능력으로 엮이는 팀 빌딩의 새로운 기준',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOON_TEAM_48_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOON_TEAM_48_FE',
    releaseLink: '',
    image: Team48,
    pm: '김채현(명지대)',
    design: '최민서(경북대)',
    frontend: ['김사랑(울산대)', '황동헌(울산대)'],
    backend: ['주채연(가톨릭대)', '최예인(동국대)'],
  },
  {
    award: '',
    title: '기숙상점',
    content: '경제적 부담을 느끼는 기숙사생들이 재학생 인증과 실명제를 통해 신뢰할 수 있는 공동구매 플랫폼',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_49_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_49_FE',
    releaseLink: '',
    image: Team49,
    pm: '',
    design: '김승혁(가톨릭대)',
    frontend: ['임세윤(단국대)', '백지웅(가톨릭대)'],
    backend: ['장선우(동국대)', '박시현(가천대)', '정현석(경희대)'],
  },

  {
    award: '',
    title: 'Cone',
    content: '소프트하게 말하는 법, Cone',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_51_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_51_FE',
    releaseLink: '',
    image: Team51,
    pm: '이윤서(가톨릭대)',
    design: '오자현(중앙대)',
    frontend: ['권정(숙명여대)', '김동건(성균관대)'],
    backend: ['이송목(성균관대)', '김성은(숙명여대)'],
  },

  {
    award: '',
    title: '이룸소',
    content: '지원금에 대한 정보 파편화를 극복하기 위한 플랫폼',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_53_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_53_FE',
    releaseLink: '',
    image: Team53,
    pm: '김해솔(숙명여대)',
    design: '구민경(삼육대)',
    frontend: ['김은상(단국대)', '정보영(한양대(에리카))'],
    backend: ['박정은(서울여대)', '이창환(중부대)'],
  },
  {
    award: '',
    title: '페이퍼플레인',
    content: '대학생들을 위한 아이디어 공유 서비스',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_54_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOON_TEAM_54_FE',
    releaseLink: '',
    image: Team54,
    pm: '전소연(가톨릭대)',
    design: '',
    frontend: ['임명우(가천대)', '어재선(인하공업전문대)'],
    backend: ['신효환(동국대)', '최규원(세종대)'],
  },
  {
    award: '',
    title: '솜토링',
    content: '당신만의 맞춤형 멘토링 플랫폼',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_55_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_55_FE',
    releaseLink: '',
    image: Team55,
    pm: '',
    design: '',
    frontend: ['권수빈(상명대(천안))', '김윤지(동국대)'],
    backend: ['신예준(상명대(천안))', '이한음(경기대)'],
  },
  {
    award: '',
    title: 'Klay',
    content: '외국인들이 한국 생활에 적응하도록 돕는 게임형 서비스 ',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOON_TEAM_56_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOON_TEAM_56_FE',
    releaseLink: '',
    image: Team56,
    pm: '',
    design: '박채린(건국대)',
    frontend: ['김민지(숙명여대)', '박정민(청주대)'],
    backend: ['구교승(삼육대)', '이승원(가톨릭대)', '이채현(경상국립대)'],
  },
  {
    award: '',
    title: '나란',
    content: '나만의 감정일기',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_58_BE/tree/develop',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_58_FE',
    releaseLink: '',
    image: Team58,
    pm: '최민기(청주대)',
    design: '최민기(청주대)',
    frontend: ['안성민(숙명여대)', '박시현(창원대)'],
    backend: ['김시윤(세종대)', '김민지(한국공학대)', '최정희(인하공업전문대)'],
  },
  {
    award: '',
    title: '다품',
    content: '한부모 가정을 위한 커뮤니티',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_59_BE/tree/develop',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_59_FE',
    releaseLink: '',
    image: Team59,
    pm: '김규리(인천대)',
    design: '',
    frontend: ['박건률(청주대)', '김동현(대구가톨릭대)'],
    backend: ['김영인(경북대)', '김재영(청주대)', '임형준(청주대)'],
  },
  {
    award: '',
    title: '함께가치',
    content: '저소득층과 함께하는',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_60_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_60_FE',
    releaseLink: '',
    image: Team60,
    pm: '',
    design: '서정민(서경대)',
    frontend: ['김성수(삼육대)', '황주역(경북대)'],
    backend: ['강재석(인하공업전문대)', '서다빈(가톨릭대)', '김종호(울산대)'],
  },
  {
    award: '',
    title: '집잡이',
    content:
      '수도권의 주거비용 때문에 수도권 취업에 어려움을 겪는 청년들이 합리적인 거주지와 유망한 기업을 함께 확인할 수 있도록 하는 서비스',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_61_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_61_FE',
    releaseLink: '',
    image: Team61,
    pm: '김지영(덕성여대)',
    design: '',
    frontend: ['김태현(청주대)'],
    backend: ['김지운(청주대) ', '김현민(아주대)', '한시현(고려대(세종)'],
  },
  {
    award: '',
    title: '여름지기',
    content: '청년 농부를 위한 커뮤니티',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOON_TEAM_62_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_62_FE',
    releaseLink: '',
    image: Team62,
    pm: '',
    design: '',
    frontend: ['강유정(가톨릭대)', '최예윤(경북대)'],
    backend: ['정재웅(경북대)', '노승빈(청주대)', '조원종(단국대)'],
  },
  {
    award: '',
    title: '청공',
    content: '청년 공간 탐색 도우미',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOON_TEAM_63_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_63_FE',
    releaseLink: '',
    image: Team63,
    pm: '',
    design: '',
    frontend: ['박세영(광운대)', '이시은(한양대(에리카))'],
    backend: ['박래환(청주대)'],
  },
  {
    award: '',
    title: '주식한입',
    content: '매일 주식이 상승하는지 하락하는지 맞추는 게임 서비스',
    backendLink: 'https://github.com/9oormthon-univ/ParkRaeHwan-2024_DANPOONG_TEAM_64_BE.git',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOON_TEAM_64_FE',
    releaseLink: '',
    image: Team64,
    pm: '',
    design: '황진희(한양대(에리카))',
    frontend: ['정연찬(한양대(에리카))'],
    backend: ['방경원(한성대)'],
  },
  {
    award: '',
    title: '접신',
    content: '자기소개서 기반 AI면접 서비스',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_65_BE.git',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_65_FE',
    releaseLink: '',
    image: Team65,
    pm: '송일환(광운대)',
    design: '',
    frontend: ['김민범(경북대)', '이유현(삼육대)'],
    backend: ['서수민(명지대)', '유우석(경북대)'],
  },
  {
    award: '',
    title: '인터넷턴',
    content: '과제에서 포트폴리오로, 인턴까지',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_66_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_66_FE',
    releaseLink: '',
    image: Team66,
    pm: '',
    design: '정채희(경북대)',
    frontend: [''],
    backend: ['이현규(고려대(세종))'],
  },
  {
    award: '',
    title: '솜길',
    content: '현지인과 함께하는 사각지대 지방 관광 패키지',
    backendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_67_BE',
    frontendLink: 'https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_67_FE',
    releaseLink: '',
    image: Team67,
    pm: '임지인(인하대)',
    design: '이혜성(인천대)',
    frontend: ['조영진(청주대)'],
    backend: ['이현서(공주대)'],
  },
];

export default DanpungProject2024Data;
