export const STACKS_WITH_NAMES = [
  { id: 'ableton', name: 'Ableton Live' },
  { id: 'activitypub', name: 'ActivityPub' },
  { id: 'actix', name: 'Actix Web' },
  { id: 'adonis', name: 'AdonisJS' },
  { id: 'ae', name: 'Adobe After Effects' },
  { id: 'aiscript', name: 'AIScript' },
  { id: 'alpinejs', name: 'Alpine.js' },
  { id: 'anaconda', name: 'Anaconda' },
  { id: 'androidstudio', name: 'Android Studio' },
  { id: 'angular', name: 'Angular' },
  { id: 'ansible', name: 'Ansible' },
  { id: 'apollo', name: 'Apollo GraphQL' },
  { id: 'appwrite', name: 'Appwrite' },
  { id: 'arch', name: 'Arch Linux' },
  { id: 'arduino', name: 'Arduino' },
  { id: 'astro', name: 'Astro' },
  { id: 'atom', name: 'Atom' },
  { id: 'autocad', name: 'AutoCAD' },
  { id: 'aws', name: 'AWS' },
  { id: 'azure', name: 'Microsoft Azure' },
  { id: 'babel', name: 'Babel' },
  { id: 'bash', name: 'Bash' },
  { id: 'bitbucket', name: 'Bitbucket' },
  { id: 'blender', name: 'Blender' },
  { id: 'bootstrap', name: 'Bootstrap' },
  { id: 'c', name: 'C' },
  { id: 'cpp', name: 'C++' },
  { id: 'cs', name: 'C#' },
  { id: 'clion', name: 'CLion' },
  { id: 'clojure', name: 'Clojure' },
  { id: 'cloudflare', name: 'Cloudflare' },
  { id: 'cmake', name: 'CMake' },
  { id: 'codepen', name: 'CodePen' },
  { id: 'coffeescript', name: 'CoffeeScript' },
  { id: 'css', name: 'CSS' },
  { id: 'cypress', name: 'Cypress' },
  { id: 'dart', name: 'Dart' },
  { id: 'debian', name: 'Debian' },
  { id: 'deno', name: 'Deno' },
  { id: 'devto', name: 'Dev.to' },
  { id: 'discord', name: 'Discord' },
  { id: 'django', name: 'Django' },
  { id: 'docker', name: 'Docker' },
  { id: 'dotnet', name: '.NET' },
  { id: 'dynamodb', name: 'DynamoDB' },
  { id: 'eclipse', name: 'Eclipse' },
  { id: 'elasticsearch', name: 'Elasticsearch' },
  { id: 'electron', name: 'Electron.js' },
  { id: 'elixir', name: 'Elixir' },
  { id: 'express', name: 'Express.js' },
  { id: 'fastapi', name: 'FastAPI' },
  { id: 'figma', name: 'Figma' },
  { id: 'firebase', name: 'Firebase' },
  { id: 'flask', name: 'Flask' },
  { id: 'flutter', name: 'Flutter' },
  { id: 'gatsby', name: 'Gatsby' },
  { id: 'gcp', name: 'Google Cloud Platform' },
  { id: 'git', name: 'Git' },
  { id: 'github', name: 'GitHub' },
  { id: 'gitlab', name: 'GitLab' },
  { id: 'go', name: 'Go (Golang)' },
  { id: 'graphql', name: 'GraphQL' },
  { id: 'haskell', name: 'Haskell' },
  { id: 'heroku', name: 'Heroku' },
  { id: 'html', name: 'HTML' },
  { id: 'java', name: 'Java' },
  { id: 'js', name: 'JavaScript' },
  { id: 'jenkins', name: 'Jenkins' },
  { id: 'jest', name: 'Jest' },
  { id: 'jquery', name: 'jQuery' },
  { id: 'kafka', name: 'Apache Kafka' },
  { id: 'kali', name: 'Kali Linux' },
  { id: 'kotlin', name: 'Kotlin' },
  { id: 'kubernetes', name: 'Kubernetes' },
  { id: 'laravel', name: 'Laravel' },
  { id: 'linux', name: 'Linux' },
  { id: 'lua', name: 'Lua' },
  { id: 'mongodb', name: 'MongoDB' },
  { id: 'mysql', name: 'MySQL' },
  { id: 'nestjs', name: 'NestJS' },
  { id: 'nextjs', name: 'Next.js' },
  { id: 'nginx', name: 'NGINX' },
  { id: 'nodejs', name: 'Node.js' },
  { id: 'npm', name: 'npm' },
  { id: 'nuxtjs', name: 'Nuxt.js' },
  { id: 'php', name: 'PHP' },
  { id: 'postgres', name: 'PostgreSQL' },
  { id: 'postman', name: 'Postman' },
  { id: 'powershell', name: 'PowerShell' },
  { id: 'prisma', name: 'Prisma' },
  { id: 'py', name: 'Python' },
  { id: 'pytorch', name: 'PyTorch' },
  { id: 'rails', name: 'Ruby on Rails' },
  { id: 'react', name: 'React.js' },
  { id: 'redis', name: 'Redis' },
  { id: 'redux', name: 'Redux' },
  { id: 'remix', name: 'Remix' },
  { id: 'rust', name: 'Rust' },
  { id: 'sass', name: 'SASS' },
  { id: 'spring', name: 'Spring Boot' },
  { id: 'sqlite', name: 'SQLite' },
  { id: 'styledcomponents', name: 'Styled Components' },
  { id: 'supabase', name: 'Supabase' },
  { id: 'svelte', name: 'Svelte' },
  { id: 'swift', name: 'Swift' },
  { id: 'tailwind', name: 'Tailwind CSS' },
  { id: 'terraform', name: 'Terraform' },
  { id: 'threejs', name: 'Three.js' },
  { id: 'ts', name: 'TypeScript' },
  { id: 'ubuntu', name: 'Ubuntu' },
  { id: 'unity', name: 'Unity' },
  { id: 'unreal', name: 'Unreal Engine' },
  { id: 'vercel', name: 'Vercel' },
  { id: 'vim', name: 'Vim' },
  { id: 'vite', name: 'Vite' },
  { id: 'vscode', name: 'VS Code' },
  { id: 'vue', name: 'Vue.js' },
  { id: 'webpack', name: 'Webpack' },
  { id: 'wordpress', name: 'WordPress' },
  { id: 'yarn', name: 'Yarn' },
  { id: 'zig', name: 'Zig' },
] as const;

export type Stack = (typeof STACKS_WITH_NAMES)[number];
