const mockIdeas = [
  {
    id: 1,
    topic: '해커톤 주제1',
    title: 'AI 기반 코드 리뷰 시스템',
    description: 'AI를 활용하여 코드 리뷰를 자동화하고, 개선점을 추천하는 시스템입니다.',
    status: '모집 중',
  },
  {
    id: 2,
    topic: '해커톤 주제2',
    title: '메타버스 협업 툴',
    description: 'VR을 활용한 가상 회의 플랫폼으로, 현실감 있는 원격 협업을 제공합니다.',
    status: '모집 완료',
  },
  {
    id: 3,
    topic: '해커톤 주제3',
    title: '블록체인 기반 전자 계약 시스템',
    description: '스마트 컨트랙트를 활용하여 안전한 전자 계약을 제공하는 서비스입니다.',
    status: '모집 중',
  },
  {
    id: 4,
    topic: '해커톤 주제1',
    title: '헬스케어 챗봇',
    description: 'AI 기반 챗봇을 활용하여 실시간 건강 상담을 제공하는 시스템입니다.',
    status: '모집 중',
  },
  {
    id: 5,
    topic: '해커톤 주제2',
    title: '온라인 강의 요약 AI',
    description: '강의 내용을 요약해주는 AI를 활용하여 학습 효율을 극대화하는 서비스입니다.',
    status: '모집 완료',
  },
  {
    id: 6,
    topic: '해커톤 주제3',
    title: '친환경 배송 플랫폼',
    description: '탄소 배출을 줄일 수 있는 친환경적인 물류 및 배송 최적화 플랫폼.',
    status: '모집 중',
  },
  {
    id: 7,
    topic: '해커톤 주제1',
    title: '소셜 네트워크 AI 감성 분석',
    description: 'SNS 데이터를 분석하여 감성 트렌드를 파악하는 AI 시스템.',
    status: '모집 완료',
  },
  {
    id: 8,
    topic: '해커톤 주제2',
    title: '음식물 쓰레기 관리 앱',
    description: '음식물 쓰레기 배출량을 분석하고 줄이는 솔루션을 제공하는 애플리케이션.',
    status: '모집 중',
  },
  {
    id: 9,
    topic: '해커톤 주제3',
    title: '스마트 홈 에너지 절약 시스템',
    description: 'IoT 기반의 스마트 홈 기기를 활용하여 에너지 사용량을 최적화하는 서비스.',
    status: '모집 완료',
  },
  {
    id: 10,
    topic: '해커톤 주제1',
    title: 'AI 기반 스마트 쇼핑 도우미',
    description: '사용자 취향을 분석하여 최적의 상품을 추천하는 AI 쇼핑 어시스턴트.',
    status: '모집 중',
  },
  {
    id: 11,
    topic: '해커톤 주제2',
    title: 'AR 가구 배치 시뮬레이터',
    description: 'AR 기술을 활용하여 가구 배치를 미리 확인하는 인테리어 시뮬레이터.',
    status: '모집 완료',
  },
  {
    id: 12,
    topic: '해커톤 주제3',
    title: '실시간 자연재해 감지 및 경고 시스템',
    description: '위성 데이터와 AI 분석을 활용하여 자연재해 발생을 감지하는 플랫폼.',
    status: '모집 중',
  },
  {
    id: 13,
    topic: '해커톤 주제1',
    title: 'AI 번역 및 음성 합성 플랫폼',
    description: '다국어 실시간 번역 및 자연스러운 음성 합성을 지원하는 서비스.',
    status: '모집 완료',
  },
];

export default mockIdeas;
